name: Daily Zoom Attendance

on:
  schedule:
    - cron: "30 19 * * *"   # 01:00 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: Configure DB

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Zoom attendance ingestion
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}

          HOST: ${{ secrets.HOST }}
          DBNAME: ${{ secrets.DBNAME }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
        run: python zoom_attendance_to_db.py
